# Generated by Django 5.1.7 on 2025-04-17 13:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_add_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='creerChasse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='date_activation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='date_desactivation',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
