# Generated by Django 5.1.7 on 2025-06-03 08:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_creerchasse_user_date_activation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('couleur', models.CharField(max_length=16)),
                ('prix', models.FloatField()),
                ('date_fin', models.DateTimeField()),
                ('nombre_participant', models.IntegerField()),
                ('lieu', models.CharField(max_length=255)),
                ('monde', models.CharField(max_length=255)),
                ('est_prive', models.BooleanField()),
                ('messagerie_est_actif', models.BooleanField()),
                ('participants', models.ManyToManyField(related_name='chasses_participants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
