# Generated by Django 5.1.7 on 2025-06-03 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_chasse'),
    ]

    operations = [
        migrations.AddField(
            model_name='chasse',
            name='createur',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='chasses_crees', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
