# Generated by Django 5.1.7 on 2025-06-03 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_chasse_createur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='chasse',
            name='createur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chasse_createur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chasse',
            name='participants',
            field=models.ManyToManyField(related_name='chasse_participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chasse',
            name='themes',
            field=models.ManyToManyField(related_name='chasse_themes', to='app.theme'),
        ),
    ]
