# Generated by Django 5.1.7 on 2025-06-16 15:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_theme_alter_chasse_createur_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lieu', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='chasse',
            name='themes',
        ),
        migrations.AlterField(
            model_name='chasse',
            name='participants',
            field=models.ManyToManyField(related_name='chasses_participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chasse',
            name='caches',
            field=models.ManyToManyField(related_name='chasses_caches', to='app.cache'),
        ),
    ]
