# Generated by Django 5.1.7 on 2025-06-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_cache_remove_chasse_themes_alter_chasse_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chasse',
            name='themes',
            field=models.ManyToManyField(related_name='chasses_themes', to='app.theme'),
        ),
    ]
