# Generated by Django 5.1.7 on 2025-06-16 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_chasse_themes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='solde_coronne',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='Etape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('chasse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='app.chasse')),
                ('participants', models.ManyToManyField(related_name='etapes_participants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
