# Generated by Django 5.1.7 on 2025-06-16 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_user_solde_coronne_etape'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recompense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('valeur', models.FloatField()),
                ('cache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recompenses', to='app.cache')),
            ],
        ),
        migrations.CreateModel(
            name='Artefact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('valeur', models.CharField(max_length=255)),
                ('recompense', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.recompense')),
            ],
        ),
    ]
