# Generated by Django 5.1.7 on 2025-06-16 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_recompense_artefact'),
    ]

    operations = [
        migrations.AddField(
            model_name='artefact',
            name='possesseur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artefacts_possesseur', to=settings.AUTH_USER_MODEL),
        ),
    ]
