# Generated by Django 5.1.7 on 2025-06-26 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='solde_coronne',
            new_name='solde_couronne',
        ),
    ]
