# Generated by Django 5.1.7 on 2025-06-26 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        # Opération de renommage supprimée car le champ existe déjà avec le bon nom
        migrations.CreateModel(
            name='RecompenseReclamable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('couronnes', 'Couronnes'), ('objet_rare', 'Objet Rare'), ('autre', 'Autre')], max_length=50)),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('quantite', models.IntegerField(blank=True, null=True)),
                ('raison', models.CharField(blank=True, max_length=255, null=True)),
                ('reclamable', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_reclamation', models.DateTimeField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recompenses_reclamables', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BadgeUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_obtention', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges_utilisateurs', to='app.badge')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges_utilisateur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('badge', 'utilisateur')},
            },
        ),
    ]
