# Generated by Django 5.1.7 on 2025-06-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_solde_coronne_user_solde_couronne'),
    ]

    operations = [
        migrations.AddField(
            model_name='chasse',
            name='date_debut',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='chasse',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
