# Generated by Django 5.1.7 on 2025-06-26 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_badge_rename_solde_coronne_user_solde_couronne_and_more'),
        ('app', '0014_chasse_date_debut_chasse_description'),
    ]

    operations = [
    ]
