# Generated by Django 5.1.7 on 2025-06-06 09:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_chasse_createur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lieu', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='chasse',
            name='caches',
            field=models.ManyToManyField(related_name='chasses_caches', to=settings.AUTH_USER_MODEL),
        ),
    ]
